# Generated by Django 5.2.8 on 2025-11-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_membresia_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='routines', to='main.userprofile'),
        ),
    ]
